#!/usr/bin/env bash
#SBATCH --nodes=1 --ntasks=16
#SBATCH -o C016_04_8MPI.%J.out
#SBATCH --exclusive
#SBATCH -p basic-slurm

export OMP_NUM_THREADS=1
export OMP_PROC_BIND=TRUE
/usr/bin/time code_saturne run

